version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: workforce_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"     # AMQP port
      - "15672:15672"   # Management UI
    restart: unless-stopped